on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  build:
    name: Build apk and upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - name: Build Apk 📦
        run: flutter build apk
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: miteru.apk
          path: build/app/outputs/apk/release/app-release.apk
      
