name: Build on Push

on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  build:
    name: Build apk and upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'
          distribution: 'zulu'
          
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - name: Build Apk 📦
        run: flutter build apk
        
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: miteru.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      
